Add clients page
Materials-Consortia/materials-consortia.github.io pull request #30
Opened 2020-11-23 14:08 UTC by CasperWA

The clients page showcases the various available clients to query OPTIMADE databases.

There are currently 3 different clients:
- Swagger/OpenAPI UI (petstore.swagger.io)
- MaterialsCloud Tool (materialscloud.org/optimadeclient)
- optimade.science

To access this new page, a new menu item "Try It!" has been added.

I have requested reviews from the "management", providers I have explicitly mentioned, and client creators, and would especially like all entities who are mentioned on the new page to give their consent.

2020-11-23 14:17 UTC, shyamd approved these changes

2020-11-23 14:26 UTC, ml-evs approved these changes
:+1:

2020-11-24 10:14 UTC, CasperWA commented
@blokhin is this page okay with you? Since it mentions you by name and points to your website, I want to make sure you're okay with it and/or if the text should be changed slightly.

@ml-evs Could I perhaps ask you to test this locally as well, like you did #29? Specifically if the menu does not look weird now with the extra entry.

2020-11-24 14:14 UTC, ml-evs requested changes
The menu is now a bit wide (wraps onto two lines when given < half the screen width at 1080p), but no big deal. Could potentially remove "Contributors" as a top-level link and put it under the About section and/or move forums to a link under Documentation?

I like the Try It page though (modulo minor fixes below), perhaps the menu button could be a brighter colour (OPTIMADE blue/red?) for emphasis? I guess a redesign is probably on the horizon anyway...

2020-11-24 14:14 UTC, ml-evs commented on clients.md
> +An [open-source](https://github.com/CasperWA/voila-optimade-client){target=_blank} web and local executable client developed by [Casper W. Andersen (THEOS, EPFL)](https://casper.welzel.nu){target=_bl
Some of the link rendering is broken:

```suggestion
An [open-source](https://github.com/CasperWA/voila-optimade-client){:target=_blank} web and local executable client developed by [Casper W. Andersen (THEOS, EPFL)](https://casper.welzel.nu){:target=_blank} using [Voilà](https://voila.readthedocs.io){:target=_blank} is available on [MaterialsCloud](https://materialscloud.org){:target=_blank}.
```

2020-11-24 14:24 UTC, blokhin commented
Please, could you delete the _optimade.science_ for now? The current version is malfunctioning, and we are about to roll out the new major update soon (completely rewritten). I will PR it here as soon as it is ready.

2020-11-24 15:59 UTC, CasperWA commented
> The menu is now a bit wide (wraps onto two lines when given < half the screen width at 1080p), but no big deal. Could potentially remove "Contributors" as a top-level link and put it under the About section and/or move forums to a link under Documentation?

I can find pros and cons for keeping/removing them:
The Contributors list is quite a long one, not really fitting for a landing page, but it is indeed related to who the consortium is.
For the forum to be used, it needs a special place, hence a menu item makes sense, however, it again indeed goes under the "umbrella" of relating to documentation - so it would make sense to simply highlight on the documentation page. But I would need some input on this idea from @gmrigna, @shyamd and @mkhorton (who I believe set up this forum?).

> (...) perhaps the menu button could be a brighter colour (OPTIMADE blue/red?) for emphasis? I guess a redesign is probably on the horizon anyway...

I was thinking the exact same thing! To catch the eye, but looking at it I would have to change a lot of the CSS and HTML design it seems. Not worth it for now :sweat_smile: 
And I don't know that a redesign in on the horizon as we already just did one...

2020-11-24 22:56 UTC, ml-evs approved these changes
Fair enough, will just approve and let others decide.

I've just added b450a5d which highlights the Try It button in blue, feel free to revert before merging.

2020-11-27 11:06 UTC, gmrigna commented
I will leave to @shyamd and @mkhorton to comment about the "Forum" button. I have no particular idea about where to place it...

2020-11-27 11:21 UTC, gmrigna commented
The blue button looks good to me...

2020-11-27 11:22 UTC, gmrigna approved these changes

2021-03-26 17:05 UTC, ml-evs commented
> @CasperWA could you revert this commit? [optimade.science](https://optimade.science) is back again : )

I've just done this, so we should be good to go!

2021-03-26 17:06 UTC, ml-evs commented
@CasperWA could you check that the changes (URLs etc) you made initially are still valid, then merge when you are happy?

2021-03-26 17:41 UTC, blokhin approved these changes

2021-03-26 17:42 UTC, blokhin commented
I see the command `{:target=_blank}` is not rendered properly.

2021-03-28 20:01 UTC, ml-evs commented
> I see the command `{:target=_blank}` is not rendered properly.

That's fine, it works in the rendered HTML, we don't have to worry about the markdown here

2021-03-28 20:36 UTC, ml-evs commented
I've tested all the client links locally, so I'm going to merge this so as not to block #31.

2021-03-28 20:36 UTC, merged

2021-03-29 05:29 UTC, gmrigna commented
In the "Swagger" section, the links to the Materials Project and the Materials Cloud lead to "Failed to load API definition."
The problem may be related to cross-origin (CORS) issue ("Access-Control-Allow-Origin").

2021-03-29 08:45 UTC, CasperWA commented
> In the "Swagger" section, the links to the Materials Project and the Materials Cloud lead to "Failed to load API definition."
> The problem may be related to cross-origin (CORS) issue ("Access-Control-Allow-Origin").

For Materials Cloud, I think this is related to the issue that one cannot reach the generated OpenAPI JSON for the implementations. See also Materials-Consortia/optimade-python-tools#520, which I think is the cause of the endpoint not being reachable.